/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import org.junit.Test;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

import static org.junit.Assert.*;

public class AppTest {
    public AppTest() throws FileNotFoundException {
    }

    // testing json reading
    Gson gson = new Gson();
    Scanner reader = new Scanner(new File("src/test/resources/testJson.json"));
    String firstLine = reader.nextLine();


    @Test
    public void testToReadJson() {
        assertEquals("[",
                "[",
                firstLine
        );
    }

    // check that file exists
    // assistance for this thanks to Jon Veach
    @Test
    public void testForFileExistance() {
        File testPath = new File("src/main/resources/recentquotes.json");
        boolean exists = testPath.exists();
        assertTrue(exists);
    }

    // NEED a test to check if a quote or an author exists in the list

}
