/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;

import java.io.*;
import java.net.HttpURLConnection;
import java.net.URL;

import static java.lang.System.*;

public class App {

    public static void main(String[] args) throws FileNotFoundException {
        try {
            cacheJokeToFile();
        } catch (IOException e) {
            out.println("API could not be reached.");
            readFromArray();
        }
    }

    // put joke from API in JSON file
    private static void cacheJokeToFile() throws IOException {
        // access key value pairs from the class Quote constructor to format what we get from the API
        Quote joke = new Quote("The Universe", new App().getDataFromAPI());
        // print joke to console
        out.println(joke);
        // use the file reader to access the JSON file and create new gson
        Reader fileReader = new FileReader(new File("src/main/resources/recentquotes.json"));
        Gson gson = new Gson();
        // build Quotes array
        Quote[] quotesArray = gson.fromJson(fileReader, Quote[].class);
        // make a new array one element longer than the previous
        Quote[] newQuotesArray = new Quote[quotesArray.length + 1];
        // add the new joke and all the original quotes/jokes to the new array
        arraycopy(quotesArray, 0, newQuotesArray, 0, quotesArray.length); // I think this is where the Monroe quote is getting stuck. Need to follow up on this.
        // add new joke to end of the new array
        newQuotesArray[newQuotesArray.length - 1] = joke;
        // replace current content in json file with the new array content
        FileWriter jokeWriter = new FileWriter("src/main/resources/apijoke.json");
        gson.toJson(newQuotesArray, jokeWriter);
        // close the quoteWriter
        jokeWriter.close();
    }

    // get a random quote from an array of quotes using a helper method
    public static Quote getRandomQuote(Quote[] quotes) {
        // get random number
        int index = (int)(Math.random() * quotes.length);
        return quotes[index];
    }

    String getDataFromAPI() throws IOException {
        URL jqueryUrl = new URL("https://geek-jokes.sameerkumar.website/api");
        HttpURLConnection connection = (HttpURLConnection) jqueryUrl.openConnection();
        BufferedReader reader = new BufferedReader(new InputStreamReader(connection.getInputStream()));
        StringBuilder data = new StringBuilder();
        String line = reader.readLine();

        while (line != null) {
            data.append(line);
            line = reader.readLine();
        }
        return data.toString();
    }

    // get a random quote from the saved array when the API is not found
    static void readFromArray() throws FileNotFoundException {
        // read all the quotes/jokes in the JSON file
        Reader fileReader = new FileReader(new File("src/main/resources/recentquotes.json"));
        Gson gson = new Gson();
        // build Quotes array
        Quote[] quotesArray = gson.fromJson(fileReader, Quote[].class);
        // print out a random quote
        out.println(getRandomQuote(quotesArray));
    }
}